[package]
name = "pequi-ic-ufg"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["BrianMath", "ArthurTrindade"]
license = "MIT"
description = "Report template for UFG students"
keywords = ["UFG", "report", "ic", "brasil", "brazil"]
repository = "https://github.com/BrianMath/pequi-ic-ufg"
categories = ["report"]
compiler = "0.12.0"

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
